---

- hosts: radiopi
  remote_user: pi
  sudo: yes

  vars:
    radiopi_version: v0.5.0

  tasks:
    - include_vars: vars/secret.yml
    - name: resize rootfs
      copy: src=files/raspi-expand-rootfs.sh dest=/usr/local/bin/raspi-expand-rootfs.sh mode=0755
      notify:
        - exec_resize_rootfs
      tags:
        - init

    - name: Remove raspi-config prompt
      lineinfile: dest=/etc/ld.so.preload regexp="libcofi_rpi.so" state=absent

    - name: configure apt
      file: path=/etc/apt/sources.list.d/raspi.list state=absent
    - copy: src=files/sources.list dest=/etc/apt/sources.list

    - name: Update system
      apt: upgrade=dist update_cache=yes dpkg_options='force-confold,force-confdef'
      tags:
        - systemupdate

    - name: ensure network connection
      cron:
        name: "ensure network"
        minute: "*/2"
        job: 'bash -c "ping -q -c2 192.168.1.1 || (ifdown --force wlan0 ;ifup wlan0 )"'

    - name: configure WiFi
      template:
        dest: /etc/network/interfaces
        src: templates/interfaces.j2

    - name: install required packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - mpg123
        - unzip


    - name: create assets dir
      file: dest=/opt/ansible-assets state=directory

    - name: download radiopi server
      command: "curl -L https://gobuilder.me/get/github.com/Luzifer/radiopi/radiopi_{{ radiopi_version }}_linux-arm.zip -o /opt/ansible-assets/radiopi_{{ radiopi_version }}_linux-arm.zip"
      args:
        creates: "/opt/ansible-assets/radiopi_{{ radiopi_version }}_linux-arm.zip"

    - name: install radiopi server
      shell: "unzip -o /opt/ansible-assets/radiopi_{{ radiopi_version }}_linux-arm.zip && mv radiopi/radiopi /usr/local/bin/radiopi_{{ radiopi_version }}"
      args:
        chdir: /tmp/
        creates: "/usr/local/bin/radiopi_{{ radiopi_version }}"

    - name: Link radiopi server
      file:
        src: "/usr/local/bin/radiopi_{{ radiopi_version }}"
        dest: /usr/local/bin/radiopi
        state: link
      notify:
        - restart radiopi


    - name: Start radiopi-server on startup
      copy: src=files/bash_profile dest=/home/pi/.bash_profile owner=pi group=pi
      notify:
        - restart radiopi

    - name: Login pi at startup
      replace: dest=/etc/inittab regexp='^1:.*getty.*$' replace='1:2345:respawn:/usr/local/bin/radiopi'
      replace: dest=/etc/inittab regexp='^1:.*RPICFG_TO_DISABLE' replace='1:2345:respawn:/usr/local/bin/radiopi'
      notify:
        - reboot

    - name: Configure favorite stations
      copy:
        src: files/favorites.yml
        dest: /home/pi/.radiopi.favorites

  handlers:
    - name: restart radiopi
      command: killall radiopi

    - name: exec_resize_rootfs
      command: /usr/local/bin/raspi-expand-rootfs.sh
      notify:
        - reboot

    - name: reboot
      command: reboot
